<?php
    include('header.phtml');
    $url= "https://pidash-kaos1910.c9users.io";
    $cart = file_get_contents($url . "/api/cart");
    $cart = json_decode($cart);
    // TODO get product from product id...
    $products = file_get_contents($url . "/api/products/");
    $products = json_decode($products);
    
?>
<div class="container">
    <h1>Cart</h1>
    <table class="table">
        <tr>
            <th>ProductId</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
        </tr>
        <?php 
        foreach($cart as $item) {
            $product = file_get_contents($url . "/api/products/" . $item->productid);
            $product = json_decode($product);
            if($product != NULL) {
            echo "<tr>";
            echo "<td>" . $product->id . "</td>";
            echo "<td>" . $item->quantity . "</td>";
            echo "<td>" . $product->price . "</td>";
            echo "<td>" . ($product->price * $item->quantity) . "</td>";
            echo "</tr>";
            }
         }
   ?>
    </table>
</div>
<?php
    include('footer.phtml');
?>

