<?php
    include('header.phtml');
    $url= "https://pidash-kaos1910.c9users.io";
    $cart = file_get_contents($url . "/api/cart");
    $cart = json_decode($cart);
    // TODO get product from product id...
    $products = file_get_contents($url . "/api/products/");
    $products = json_decode($products);
    
?>
<div class="container" id="main">
    <h1>Cart</h1>
    <cart></cart>
</div>

<template id="cart">
    <table class="table">
        <tr>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
        </tr>
        <tr v-for="item in cart">
            <td>{{ item.name }}</td>
            <td>{{ item.price }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.quantity * item.price }}</td>
        </tr>
    </table>
</template>
<script src="js/app.js"></script>
<?php
    include('footer.phtml');
?>

