<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Pi-Dash</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>   
        <link rel="shortcut icon" type="image/jpg" href="https://cloud.tranos.de/seafhttp/files/d0282546-a3b1-420f-975c-02c22dc66517/20170114_180749.jpg">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="https://unpkg.com/notie/dist/notie.min.css">
        <link rel="stylesheet" type="text/css" href="css/style.css">
    </head>
    <body>
<?php include("nav.phtml"); ?>