<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Pi-Dash</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>       
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <script src="https://unpkg.com/vue/dist/vue.js"></script>
        <script src="https://cdn.jsdelivr.net/vue.resource/1.2.0/vue-resource.min.js"></script>
    </head>
    <body>
<?php include("nav.phtml"); ?>