<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Pi-Dash</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>       
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="https://unpkg.com/notie/dist/notie.min.css">
        <link rel="stylesheet" type="text/css" href="css/style.css">
    </head>
    <body>
<?php include("nav.phtml"); ?>