<?php include_once("header.phtml") ?>
  <style>
            .home {
                padding: 0 0 0 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #54adef;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 50px;
                font-weight: 200;
                margin-bottom: 0;
            }
            a {
                text-decoration: none;
                color: #54adef;
            }
        </style>
        <div class="container home">
        <h1>Pi-Dash API</h1>
        <div>This is an API endpoint for testing purposes of the Pi-Dash project.</div>
        <p>See: <a target="_blank" href="https://github.com/kai-oswald/Pi-Dash/wiki/API-Docs">API-Docs</a></p> 
        <img width="1000" height="500" src="https://cloud.tranos.de/seafhttp/files/d0282546-a3b1-420f-975c-02c22dc66517/20170114_180749.jpg"/>
        </div>
<?php include_once("footer.phtml") ?>