<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Pi-Dash API</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #54adef;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
            a {
                text-decoration: none;
                color: #54adef;
            }
        </style>
    </head>
    <body>
        <h1>Pi-Dash API</h1>
        <div>This is an API endpoint for testing purposes of the Pi-Dash project.</div>
        <p>See: <a target="_blank" href="https://github.com/kai-oswald/Pi-Dash/wiki/API-Docs">API-Docs</a></p>    
    </body>
</html>
