<?php
    include_once("header.phtml");
?>

<div id="main" class="container">
    <products></products>
</div>
<template id="products">
    <div>
    <div class="row" style="margin-bottom: 20px;">
    <div class="btn btn-primary" v-on:click="newProduct">New</div>
    </div>
    <div class="row">
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
        <th></th>
      </tr>
      <tr v-for="product in products">
        <td>{{ product.id }}</td>
        <td><input type="text" v-model="product.name" v-on:focus="getProduct(product)" v-on:blur="updateProduct(product)"/></td>
        <td><input min="0" type="number" step="0.01" v-model="product.price" v-on:focus="getProduct(product)" v-on:blur="updateProduct(product)" /></td>
        <td><div class="btn btn-danger btn-xs pull-right" v-on:click="deleteProduct(product)"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></div></td>
      </tr>
    </table>
    </div>
    <div class="row">
    <product v-on:save-product="updateProducts"></product>
    </div>
    </div>
</template>

<template id="product">
    <div id="productModal" class="modal fade" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Add new Product</h4>
          </div>
          <div class="modal-body">
          <form class="form-horizontal">
            <div class="form-group">
                <label for="inputName" class="col-sm-2 control-label">Name</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="inputName" placeholder="Name" v-model="product.name">
                </div>
              </div>
              <div class="form-group">
                <label for="inputPrice" class="col-sm-2 control-label">Price</label>
                <div class="col-sm-10">
                  <input type="number" min="0" step="0.01" class="form-control" id="inputPrice" placeholder="Price" v-model="product.price">
                </div>
              </div>
          </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" v-on:click="saveProduct">Save changes</button>
          </div>
        </div>
      </div>
    </div>
</template>
<?php 
    include_once("footer.phtml");
?>